from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class FieldDefinition(BaseModel):
    name: str
    label: str
    type: Literal["number", "boolean", "enum", "date", "multi_select"]
    options: list[str] | None = None
    unit: str | None = None
    required: bool = True


TIER1_FIELDS: dict[str, list[FieldDefinition]] = {
    "aml": [
        FieldDefinition(name="age", label="Age", type="number", unit="years"),
        FieldDefinition(name="ecog", label="ECOG Performance Status", type="enum", options=["0", "1", "2", "3", "4"]),
        FieldDefinition(name="aml_subtype", label="AML Subtype", type="enum", options=["de_novo", "secondary", "t_aml"]),
        FieldDefinition(name="disease_status", label="Disease Status", type="enum", options=["newly_diagnosed", "relapsed", "refractory", "remission"]),
        FieldDefinition(name="prior_lines", label="Prior Lines of Therapy", type="number"),
        FieldDefinition(name="prior_venetoclax", label="Prior Venetoclax", type="boolean"),
        FieldDefinition(name="prior_hma", label="Prior HMA", type="boolean"),
        FieldDefinition(name="prior_transplant", label="Prior Transplant", type="boolean"),
        FieldDefinition(name="flt3_status", label="FLT3-ITD/TKD", type="enum", options=["yes", "no", "unknown"]),
        FieldDefinition(name="idh1_status", label="IDH1", type="enum", options=["yes", "no", "unknown"]),
        FieldDefinition(name="idh2_status", label="IDH2", type="enum", options=["yes", "no", "unknown"]),
        FieldDefinition(name="npm1_status", label="NPM1", type="enum", options=["yes", "no", "unknown"]),
        FieldDefinition(name="tp53_status", label="TP53", type="enum", options=["yes", "no", "unknown"]),
        FieldDefinition(name="eln_2022_risk", label="ELN 2022 Risk", type="enum", options=["favorable", "intermediate", "adverse", "unknown"]),
        FieldDefinition(name="anc", label="ANC", type="number", unit="cells/uL"),
        FieldDefinition(name="plt", label="Platelets", type="number", unit="x10^9/L"),
        FieldDefinition(name="cr", label="Creatinine", type="number", unit="mg/dL"),
        FieldDefinition(name="bili", label="Total Bilirubin", type="number", unit="mg/dL"),
        FieldDefinition(name="ast", label="AST", type="number", unit="U/L"),
        FieldDefinition(name="alt", label="ALT", type="number", unit="U/L"),
        FieldDefinition(name="lvef", label="LVEF", type="number", unit="%"),
        FieldDefinition(name="lvef_date", label="LVEF Assessment Date", type="date"),
        FieldDefinition(name="active_cns_disease", label="Active CNS Disease", type="boolean"),
        FieldDefinition(name="active_uncontrolled_infection", label="Active Uncontrolled Infection", type="boolean"),
    ],
    "all": [
        FieldDefinition(name="age", label="Age", type="number", unit="years"),
        FieldDefinition(name="ecog", label="ECOG Performance Status", type="enum", options=["0", "1", "2", "3", "4"]),
        FieldDefinition(name="all_subtype", label="ALL Subtype", type="enum", options=["b_cell", "t_cell"]),
        FieldDefinition(name="ph_bcr_abl", label="Philadelphia Chromosome/BCR-ABL", type="enum", options=["positive", "negative", "unknown"]),
        FieldDefinition(name="ph_like", label="Ph-like", type="enum", options=["yes", "no", "unknown"]),
        FieldDefinition(name="disease_status", label="Disease Status", type="enum", options=["newly_diagnosed", "relapsed", "refractory", "remission"]),
        FieldDefinition(name="prior_lines", label="Prior Lines of Therapy", type="number"),
        FieldDefinition(name="prior_blinatumomab", label="Prior Blinatumomab", type="boolean"),
        FieldDefinition(name="prior_inotuzumab", label="Prior Inotuzumab", type="boolean"),
        FieldDefinition(name="prior_car_t", label="Prior CAR-T", type="boolean"),
        FieldDefinition(name="cns_involvement", label="CNS Involvement", type="enum", options=["none", "cns1", "cns2", "cns3"]),
        FieldDefinition(name="anc", label="ANC", type="number", unit="cells/uL"),
        FieldDefinition(name="plt", label="Platelets", type="number", unit="x10^9/L"),
        FieldDefinition(name="cr", label="Creatinine", type="number", unit="mg/dL"),
        FieldDefinition(name="bili", label="Total Bilirubin", type="number", unit="mg/dL"),
        FieldDefinition(name="ast", label="AST", type="number", unit="U/L"),
        FieldDefinition(name="alt", label="ALT", type="number", unit="U/L"),
        FieldDefinition(name="active_uncontrolled_infection", label="Active Uncontrolled Infection", type="boolean"),
    ],
    "lymphoma": [
        FieldDefinition(name="age", label="Age", type="number", unit="years"),
        FieldDefinition(name="ecog", label="ECOG Performance Status", type="enum", options=["0", "1", "2", "3", "4"]),
        FieldDefinition(name="histology", label="Histology", type="enum", options=["dlbcl", "fl", "mcl", "hl", "ptcl", "mzl", "other"]),
        FieldDefinition(name="cell_of_origin", label="Cell of Origin (DLBCL)", type="enum", options=["gcb", "non_gcb", "unknown"]),
        FieldDefinition(name="double_triple_hit", label="Double/Triple Hit", type="enum", options=["yes", "no", "unknown"]),
        FieldDefinition(name="disease_status", label="Disease Status", type="enum", options=["newly_diagnosed", "relapsed", "refractory", "remission"]),
        FieldDefinition(name="prior_lines", label="Prior Lines of Therapy", type="number"),
        FieldDefinition(name="prior_asct", label="Prior ASCT", type="boolean"),
        FieldDefinition(name="prior_car_t", label="Prior CAR-T", type="boolean"),
        FieldDefinition(name="cns_involvement", label="CNS Involvement", type="boolean"),
        FieldDefinition(name="anc", label="ANC", type="number", unit="cells/uL"),
        FieldDefinition(name="plt", label="Platelets", type="number", unit="x10^9/L"),
        FieldDefinition(name="cr", label="Creatinine", type="number", unit="mg/dL"),
        FieldDefinition(name="bili", label="Total Bilirubin", type="number", unit="mg/dL"),
        FieldDefinition(name="ast", label="AST", type="number", unit="U/L"),
        FieldDefinition(name="alt", label="ALT", type="number", unit="U/L"),
        FieldDefinition(name="active_uncontrolled_infection", label="Active Uncontrolled Infection", type="boolean"),
    ],
    "mm": [
        FieldDefinition(name="age", label="Age", type="number", unit="years"),
        FieldDefinition(name="ecog", label="ECOG Performance Status", type="enum", options=["0", "1", "2", "3", "4"]),
        FieldDefinition(name="disease_status", label="Disease Status", type="enum", options=["newly_diagnosed", "relapsed", "refractory", "remission"]),
        FieldDefinition(name="prior_lines", label="Prior Lines of Therapy", type="number"),
        FieldDefinition(name="prior_bortezomib", label="Prior Bortezomib", type="boolean"),
        FieldDefinition(name="prior_lenalidomide", label="Prior Lenalidomide", type="boolean"),
        FieldDefinition(name="prior_daratumumab", label="Prior Daratumumab", type="boolean"),
        FieldDefinition(name="triple_class_exposed", label="Triple-Class Exposed", type="boolean"),
        FieldDefinition(name="triple_class_refractory", label="Triple-Class Refractory", type="boolean"),
        FieldDefinition(name="prior_bcma_directed", label="Prior BCMA-Directed Therapy", type="enum", options=["none", "car_t", "bispecific", "both"]),
        FieldDefinition(name="del17p", label="del(17p)", type="enum", options=["yes", "no", "unknown"]),
        FieldDefinition(name="t_4_14", label="t(4;14)", type="enum", options=["yes", "no", "unknown"]),
        FieldDefinition(name="t_14_16", label="t(14;16)", type="enum", options=["yes", "no", "unknown"]),
        FieldDefinition(name="gain_1q21", label="1q21 gain", type="enum", options=["yes", "no", "unknown"]),
        FieldDefinition(name="egfr", label="eGFR", type="number", unit="mL/min/1.73m2"),
        FieldDefinition(name="calcium", label="Calcium", type="number", unit="mg/dL"),
        FieldDefinition(name="anc", label="ANC", type="number", unit="cells/uL"),
        FieldDefinition(name="plt", label="Platelets", type="number", unit="x10^9/L"),
        FieldDefinition(name="bili", label="Total Bilirubin", type="number", unit="mg/dL"),
        FieldDefinition(name="ast", label="AST", type="number", unit="U/L"),
        FieldDefinition(name="alt", label="ALT", type="number", unit="U/L"),
        FieldDefinition(name="active_uncontrolled_infection", label="Active Uncontrolled Infection", type="boolean"),
    ],
    "transplant": [
        FieldDefinition(name="age", label="Age", type="number", unit="years"),
        FieldDefinition(name="performance_status", label="KPS/ECOG Performance Status", type="enum", options=["ecog_0", "ecog_1", "ecog_2", "ecog_3", "ecog_4", "kps_100", "kps_90", "kps_80", "kps_70", "kps_60"]),
        FieldDefinition(name="underlying_diagnosis", label="Underlying Diagnosis", type="enum", options=["aml", "all", "lymphoma", "mm", "other"]),
        FieldDefinition(name="disease_status", label="Disease Status", type="enum", options=["active", "remission", "relapsed", "refractory"]),
        FieldDefinition(name="prior_transplant", label="Prior Transplant", type="boolean"),
        FieldDefinition(name="prior_transplant_type", label="Prior Transplant Type", type="enum", options=["autologous", "allogeneic", "both", "none"], required=False),
        FieldDefinition(name="hct_ci_score", label="HCT-CI Score", type="number"),
        FieldDefinition(name="donor_availability", label="Donor Availability", type="enum", options=["mrd", "mud", "haplo", "cord", "none"]),
        FieldDefinition(name="anc", label="ANC", type="number", unit="cells/uL"),
        FieldDefinition(name="plt", label="Platelets", type="number", unit="x10^9/L"),
        FieldDefinition(name="cr", label="Creatinine", type="number", unit="mg/dL"),
        FieldDefinition(name="bili", label="Total Bilirubin", type="number", unit="mg/dL"),
        FieldDefinition(name="ast", label="AST", type="number", unit="U/L"),
        FieldDefinition(name="alt", label="ALT", type="number", unit="U/L"),
        FieldDefinition(name="lvef", label="LVEF", type="number", unit="%"),
        FieldDefinition(name="lvef_date", label="LVEF Assessment Date", type="date"),
        FieldDefinition(name="fev1_percent_predicted", label="FEV1 (% Predicted)", type="number", unit="%"),
        FieldDefinition(name="dlco_percent_predicted", label="DLCO (% Predicted)", type="number", unit="%"),
        FieldDefinition(name="active_uncontrolled_infection", label="Active Uncontrolled Infection", type="boolean"),
        FieldDefinition(name="active_cns_disease", label="Active CNS Disease", type="boolean"),
    ],
    "gvhd": [
        FieldDefinition(name="age", label="Age", type="number", unit="years"),
        FieldDefinition(name="performance_status", label="KPS/ECOG Performance Status", type="enum", options=["ecog_0", "ecog_1", "ecog_2", "ecog_3", "ecog_4", "kps_100", "kps_90", "kps_80", "kps_70", "kps_60"]),
        FieldDefinition(name="gvhd_type", label="GVHD Type", type="enum", options=["acute", "chronic", "overlap"]),
        FieldDefinition(name="agvhd_grade", label="aGVHD Grade", type="enum", options=["i", "ii", "iii", "iv"], required=False),
        FieldDefinition(name="cgvhd_severity", label="cGVHD Severity", type="enum", options=["mild", "moderate", "severe"], required=False),
        FieldDefinition(name="organs_involved", label="Organs Involved", type="multi_select", options=["skin", "liver", "gi", "lung", "eye", "mouth", "fascia", "other"]),
        FieldDefinition(name="steroid_refractory", label="Steroid Refractory", type="boolean"),
        FieldDefinition(name="prednisone_mg_per_kg_per_day", label="Prednisone Dose", type="number", unit="mg/kg/day"),
        FieldDefinition(name="prior_gvhd_lines", label="Prior GVHD Therapy Lines", type="number"),
        FieldDefinition(name="months_post_transplant", label="Time Post-Transplant", type="number", unit="months"),
        FieldDefinition(name="anc", label="ANC", type="number", unit="cells/uL"),
        FieldDefinition(name="plt", label="Platelets", type="number", unit="x10^9/L"),
        FieldDefinition(name="cr", label="Creatinine", type="number", unit="mg/dL"),
        FieldDefinition(name="bili", label="Total Bilirubin", type="number", unit="mg/dL"),
        FieldDefinition(name="ast", label="AST", type="number", unit="U/L"),
        FieldDefinition(name="alt", label="ALT", type="number", unit="U/L"),
        FieldDefinition(name="active_uncontrolled_infection", label="Active Uncontrolled Infection", type="boolean"),
    ],
}
